id: P009116
initial_creation_type: ocr
source_metadata:
  id: bdr:W22061
  title: ཚེ་སྲོག་གི་འབུལ་སྐྱེས་༔ ༡༩༥༠་ལོར་དཔའ་བོའི་སྔོན་མངགས་བརྒྱ་ཤོག་ཤིན་ཅང་ནས་བོད་དུ་དཔུང་སྐྱོད་བྱས་ཚུལ་བཀོད་པ།
  author: ''
  volumes:
    69d23ad2fcc441bd85b50849f9936135:
      image_group_id: I4893
      title: ''
      volume_number: 1
      total_pages: 322
