id: opecha:P009116
initial_creation_type: ocr
source_metadata:
  id: bdr:W22061
  title: ཚེ་སྲོག་གི་འབུལ་སྐྱེས་༔ ༡༩༥༠་ལོར་དཔའ་བོའི་སྔོན་མངགས་བརྒྱ་ཤོག་ཤིན་ཅང་ནས་བོད་དུ་དཔུང་སྐྱོད་བྱས་ཚུལ་བཀོད་པ།
  volume: ''
  author: ''
